version: "3.3"
services:
  php:
    build: './php/'
    networks:
      - backend
    volumes:
      - ./public_html/:/var/www/html/
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    networks:
      - frontend
      - backend
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "8090:80"
  syslog:
    image: pbertera/syslogserver
    networks:
      - frontend
      - backend
    environment:
      SYSLOG_USERNAME: admin
      SYSLOG_PASSWORD: 1234
    ports:
      - "8091:80"
  apache:
    build: './apache/'
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "8080:80"
    volumes:
      - c:\Development\Scratch\DockerPython\MySQL\public_html:/var/www/html/
  mysql:
    image: mysql:5.7
    restart: always
    networks:
      - backend
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - mysql:/var/lib/mysql
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'

  tftpserver:
    build: './tftp/'
    networks:
      - frontend
      - backend
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '8092:5000'
    expose:
      # Opens port 3306 on the container
      - '8092'
    volumes:
      - ./tftp/source/:/app

networks:
  frontend:
  backend:

volumes:
  mysql: